name: Monitoraggio Telegram Bot

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: 

jobs:
  esegui-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clona il repository
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installa dipendenze
        run: pip install -r requirements.txt

      - name: Avvia il controllo posizione
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python telegram_bot.py
