name: Monitoraggio Telegram Bot

on:
  schedule:
    # Esegue lo script al minuto 0 di ogni ora (es. 10:00, 11:00, 12:00)
    - cron: '0 * * * *'
  # Permette di avviare il bot anche manualmente dall'interfaccia di GitHub
  workflow_dispatch: 

jobs:
  esegui-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clona il repository
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa le dipendenze
        run: |
          pip install web3 requests

      - name: Avvia il controllo posizione
        run: python telegram_bot.py
